### ISSUE TITLE
swig doesn't get run after a library has been made.

### ISSUE THREAD

**Issue by nickbailey** [keziah55/DetectorBank#5]
Makefile.am's rules to run swig (via setup.py buildDB around line 77─107) need refactoring because they are bollocks, written in a state of panic or inebriation or both.
The main challenge is that you can't just put .libs/oisughfoaiufhsv/lib_detectorbank.so or whatever as a dependency: that would just result in "don't know how to build..." because it's libtoolized and hence not automake's problem.
Brain hurts.
For the moment, from the build directory, build the library then touch ../detectorbank.i && make
```
touch ../detectorbank.i && make
( cd test/ ; ./Pytests)
```
(or to run the cpp ones too, `make check` with out cd-ing)

**Comment by keziah55** [comment]
Fix merged from build_swig branch. See [task](https://tree.taiga.io/project/kzm-detectorbank/us/7?kanban-include_attachments=1&kanban-include_tasks=1&kanban-status=2464013) for details.
