### ISSUE TITLE
Save profile to xml doesn't work

### ISSUE THREAD

**Issue by keziah55** [keziah55/DetectorBank#9]
Creating a `DetectorBank` then calling `saveProfile` doesn't add anything to ~/.config/hopfskipjump/xml

hopfskipjump.xml contians only this:
```
<?xml version="1.0" encoding="utf-8"?>
<hsj>
<protocol>v2 19 Jan 2017</protocol>
</hsj>
```

The attached file [hopfskipjump.xml.old.txt](https://github.com/keziah55/DetectorBank/files/9847117/hopfskipjump.xml.old.txt) contains expected output.

Possibly related to #6 - libcereal API change?

Releated: why do we need two dependenices (rapidxml and cereal) to read and write xml? What does each do that the other doesn't?

**Comment by nickbailey** [comment]
Commit 5f9a967 removes the notedetector tests so make check works again. I've added files with the old tests in, in case they get migrated to the new repo.

**Comment by nickbailey** [comment]
The reason for rapidxml is so may named profiles can be stored in a single file. The .xml file is more like a database than a single config. The idea is that there can be many different named profiles in the resource, and you can reconstruct the detectorbank with the parameters as it was saved without having to do all the tedious normalisation again. So cereal makes the detectorbank into xml, then the profilemanager uses rapidxml to add / replace it in the database of profiles. This seems to work OK. It's the normalisation which is faulty.

**Comment by keziah55** [comment]
Saving and loading profiles does work, don't know what was going on when I was trying it earlier.

I've added a `profiles` method to DetectorBank and ProfileManager. This returns a list of names of existing profiles (or a tuple, when wrapped to python). See 884a7e5808d7b57990d42f56d0ecd81a4a9f3f95 and 2a83cdd22bbb96481fee787a9eb60b6036769987.

Previously, `ProfileManager.profiles` returned the xml document; this has been renamed to `profilesDoc`.

**Comment by nickbailey** [comment]
Like it. I was expecting the client program to do an XML query (even easier in Python than in C!) but I'm about to use the getXML detectorbank method to look at the normalisation values in the unit tests, so doubly good as you've virtually saved me from reading the rapidxml manual again :)
